# Generated by Django 4.2.30 on 2026-08-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collective', '0013_alter_collectivecategory_id_alter_collectivecolor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='collective_product/')),
                ('stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Collective.collectiveproduct')),
            ],
            options={
                'ordering': ('color',),
            },
        ),
        migrations.AddConstraint(
            model_name='collectiveproductvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color'), name='unique_collective_product_color'),
        ),
    ]
