# Generated by Django 3.0.8 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collective', '0014_collectiveproductvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiveorderitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
