# Generated by Django 4.1.7 on 2023-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENESIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisproduct',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
