# Generated by Django 4.1.7 on 2023-03-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENESIS', '0002_genesisproduct_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisproduct',
            name='image2',
            field=models.ImageField(blank=True, upload_to='GENESIS_product/'),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='image3',
            field=models.ImageField(blank=True, upload_to='GENESIS_product/'),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='image4',
            field=models.ImageField(blank=True, upload_to='GENESIS_product/'),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='image5',
            field=models.ImageField(blank=True, upload_to='GENESIS_product/'),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='image6',
            field=models.ImageField(blank=True, upload_to='GENESIS_product/'),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='image7',
            field=models.ImageField(blank=True, upload_to='GENESIS_product/'),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='image8',
            field=models.ImageField(blank=True, upload_to='GENESIS_product/'),
        ),
    ]
