# Generated by Django 4.1.7 on 2023-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENESIS', '0003_genesisproduct_image2_genesisproduct_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisproduct',
            name='description2',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='description3',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='description4',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='description5',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='description6',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='description7',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='genesisproduct',
            name='description8',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='genesisproduct',
            name='description1',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
