# Generated by Django 4.1.7 on 2023-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENESIS', '0004_genesisproduct_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisproduct',
            name='short_desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
