import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8000/account/login/?next=/3rdAxis/');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('mufudzi@foxxmart');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('mufudzi@foxxmart.com');
  await page.getByRole('textbox', { name: 'Email address' }).press('Tab');
  await page.getByRole('link', { name: 'Forgot password?' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Hammer90*');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Shop', description: 'Online Store' }).click();
  await page.getByRole('button', { name: 'Quick cart' }).click();
  await page.getByRole('button', { name: 'Remove Axis Resin Max from' }).click();
  await page.getByRole('link', { name: 'log out outline Logout' }).click();
  await page.getByText('FOXX MART / 01 3rd AxisAdditive manufacturing').click();
  await page.getByRole('link', { name: 'Create an account' }).click();
  await page.getByRole('textbox', { name: 'Full name' }).click();
  await page.getByRole('textbox', { name: 'Full name' }).fill('Smart Shopper');
  await page.getByRole('textbox', { name: 'Full name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email address' }).fill('smart@foxxmart.com');
  await page.getByRole('textbox', { name: 'Email address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('Hammer90*');
  await page.getByRole('textbox', { name: 'Password', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Confirm password' }).fill('Hammer90*');
  await page.getByRole('button', { name: 'Create account' }).click();
  await page.getByText('FOXX MART / 01 3rd AxisAdditive manufacturing').click();
  await page.getByRole('button', { name: 'Switch to light mode' }).click();
  await page.getByText('Axis Dual Drive Extruder').click();
  await page.locator('.grid__item.precision.extruder > .action.action--button.action--compare-buy').click();
  await page.goto('http://localhost:8000/3rdAxis/');
  await page.getByText('Axis TPU Flex Lime').click();
  await page.locator('.grid__item.filament.flexible > .action.action--button.action--compare-buy').click();
  await page.getByText('Axis PETG Smoke Clear').click();
  await page.locator('.grid__item.filament.transparent > .action.action--button.action--compare-buy').click();
  await page.getByText('Axis Standard Brass Hotend').click();
  await page.locator('.grid__item.extruder > .action.action--button.action--compare-buy').first().click();
  await page.getByText('Axis Hardened Steel Hotend').click();
  await page.locator('.grid__item.extruder > .action.action--button.action--compare-buy').first().click();
  await page.locator('.grid__item.microboard > .slider > .flickity-viewport > .flickity-slider > .slider__item.is-selected > a').first().click();
  await page.getByRole('heading', { name: 'Axis MicroBoard Core' }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.locator('svg').filter({ hasText: 'Cart' }).click();
  await page.getByRole('button', { name: 'Remove Axis Standard Brass' }).click();
  await page.locator('svg').filter({ hasText: 'Cart' }).click();
  await page.getByRole('link', { name: 'Proceed to Checkout' }).click();
  await page.getByLabel('ProvinceSelect').selectOption('Western Cape');
  await page.getByRole('textbox', { name: 'Street address and number' }).click();
  await page.getByRole('textbox', { name: 'Street address and number' }).fill('12 Long Street');
  await page.getByRole('textbox', { name: 'Street address and number' }).press('Tab');
  await page.getByRole('textbox', { name: 'Apartment, suite, building or' }).fill('Apartment 4b, The Gardens');
  await page.getByRole('textbox', { name: 'Suburb / area' }).click();
  await page.getByRole('textbox', { name: 'Suburb / area' }).fill('City Bowl');
  await page.getByRole('textbox', { name: 'Suburb / area' }).press('Tab');
  await page.getByRole('textbox', { name: 'City / town' }).fill('Cape Town');
  await page.getByRole('textbox', { name: 'City / town' }).press('Tab');
  await page.getByRole('textbox', { name: 'Postal code' }).fill('8010');
  await page.getByRole('textbox', { name: 'Delivery instructions (' }).click();
  await page.getByRole('textbox', { name: 'Delivery instructions (' }).fill('Leave package with reception');
  await page.getByRole('checkbox', { name: 'Save this address for future' }).check();
  await page.getByRole('button', { name: 'Confirm test order →' }).click();
  await page.locator('iframe[name="7D7FBDD35CB7FE8A7A3E26447694B147"]').contentFrame().locator('#plugin').contentFrame().locator('embed').click();
  await page.locator('iframe[name="7D7FBDD35CB7FE8A7A3E26447694B147"]').contentFrame().getByRole('tablist').click();
  await page.getByRole('link', { name: 'person outline Profile' }).click();
  await page.goto('http://localhost:8000/account/?store=axis');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download' }).click();
  const download = await downloadPromise;
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'View PDF' }).click();
  const page1 = await page1Promise;
  await page1.locator('iframe[name="82F8710CD386CFC5DF96540FEB2D3FB4"]').contentFrame().locator('#thumbnail').click();
  await page.getByRole('link', { name: 'Continue shopping' }).click();
  await page.getByRole('button', { name: 'Filter products' }).click();
  await page.goto('http://localhost:8000/3rdAxis/');
  await page.getByRole('button', { name: 'Open navigation menu' }).click();
  await page.getByText('Out Of Stock', { exact: true }).click();
});