# Generated by Django 4.2.1 on 2023-05-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0044_remove_product_category_product_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description4',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description5',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description6',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description7',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description8',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, upload_to='Axis_product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.ImageField(blank=True, upload_to='Axis_product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image7',
            field=models.ImageField(blank=True, upload_to='Axis_product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image8',
            field=models.ImageField(blank=True, upload_to='Axis_product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description1',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Axis_product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Axis_product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Axis_product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, upload_to='Axis_product/'),
        ),
    ]
