# Generated by Django 4.2.30 on 2026-08-26

from django.db import migrations, models
import django.db.models.deletion


def create_initial_classes(apps, schema_editor):
    YogaClass = apps.get_model('COURT', 'YogaClass')
    sessions = (
        ('Sunset Flow', 0, '13:00', '15:00', 'Camps Bay Sunset'),
        ('Promenade Flow', 1, '13:00', '15:00', 'Sea Point Promenade'),
        ('Midweek Reset', 2, '13:00', '15:00', 'Newlands Catholic Church'),
        ('Temple Flow', 3, '13:00', '15:00', 'Observatory Temple'),
    )
    for name, weekday, start_time, end_time, location in sessions:
        YogaClass.objects.get_or_create(
            name=name,
            weekday=weekday,
            start_time=start_time,
            defaults={'end_time': end_time, 'location': location, 'capacity': 12, 'active': True},
        )


def remove_initial_classes(apps, schema_editor):
    YogaClass = apps.get_model('COURT', 'YogaClass')
    YogaClass.objects.filter(name__in=('Sunset Flow', 'Promenade Flow', 'Midweek Reset', 'Temple Flow')).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=160)),
                ('capacity', models.PositiveSmallIntegerField(default=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={'ordering': ('weekday', 'start_time', 'name')},
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yoga_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='COURT.yogaclass')),
            ],
            options={'ordering': ('booking_date', 'yoga_class__start_time', 'name')},
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('yoga_class', 'booking_date', 'email'), name='court_unique_booking'),
        ),
        migrations.RunPython(create_initial_classes, remove_initial_classes),
    ]
