# Generated by Django 4.1.7 on 2023-03-29 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EXODUSCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=60, null=True, unique=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='EXODUSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment Confirmed, Processing Order', 'Payment Confirmed, Processing Order'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EXODUS.exoduscustomer')),
            ],
        ),
        migrations.CreateModel(
            name='EXODUSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=500, null=True)),
                ('description1', models.TextField(max_length=2000, null=True)),
                ('description2', models.TextField(max_length=2000, null=True)),
                ('description3', models.TextField(max_length=2000, null=True)),
                ('description4', models.TextField(max_length=2000, null=True)),
                ('description5', models.TextField(max_length=2000, null=True)),
                ('description6', models.TextField(max_length=2000, null=True)),
                ('description7', models.TextField(max_length=2000, null=True)),
                ('description8', models.TextField(max_length=2000, null=True)),
                ('image1', models.ImageField(blank=True, upload_to='EXODUS_product/')),
                ('image2', models.ImageField(blank=True, upload_to='EXODUS_product/')),
                ('image3', models.ImageField(blank=True, upload_to='EXODUS_product/')),
                ('image4', models.ImageField(blank=True, upload_to='EXODUS_product/')),
                ('image5', models.ImageField(blank=True, upload_to='EXODUS_product/')),
                ('image6', models.ImageField(blank=True, upload_to='EXODUS_product/')),
                ('image7', models.ImageField(blank=True, upload_to='EXODUS_product/')),
                ('image8', models.ImageField(blank=True, upload_to='EXODUS_product/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EXODUSShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('suburb', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EXODUSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EXODUS.exodusorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EXODUS.exodusproduct')),
            ],
        ),
        migrations.AddField(
            model_name='exoduscustomer',
            name='shippingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EXODUS.exodusshippingaddress'),
        ),
        migrations.AddField(
            model_name='exoduscustomer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
